version: '3'
services:
  db:
    image: "yobasystems/alpine-mariadb:10.4.13"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-monkeyflip}"
      MYSQL_DATABASE: flip
      MYSQL_USER: monkey
      MYSQL_PASSWORD: "${DB_PASSWORD:-monkeyflip}"
      MYSQL_ROOT_HOST: "%"
    networks:
      - servers
    restart: on-failure
  server_crypto:
    image: "node:14-alpine"
    command: scripts/entrypoint.sh
    working_dir: "/usr/src"
    depends_on:
      - db
    environment:
      DB_PASSWORD: "${DB_PASSWORD:-monkeyflip}"
    volumes:
      - ".:/usr/src"
    restart: on-failure
    env_file:
      - ./.env

networks:
  servers:

volumes:
  db:
